version: '3.8'

services:
  mongodb:
    image: mongo:6
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  onboarding-app:
    build:
      context: .
    container_name: easyhire-onboarding
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017/easyhire
    networks:
      - app-network

volumes:
  mongo_data:

networks:
  app-network: